config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#welcome'
  get '/welcome', to: 'pages#welcome'
  get '/health-check', to: 'pages#health_check'
  get '/login', to: 'pages#login'
  get '/check-login', to: 'pages#check_login'
  post '/sign_in', to: 'pages#sign_in'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def health_check
    @timestamp = Time.current
  end

  def welcome
  end

  def login
  end

  def check_login
    render json: {status: 'error', code: 401, 'message': 'User or password not found'}, status: :not_found
  end

  def sign_in
    email = params[:email]
    password = params[:password]
    users = User.where(email_address: email).where(password: password)
    if users.empty?
      redirect_to login_url, alert: 'User or password not found' 
    else
      redirect_to welcome_url, notice: 'Bienvenido'
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @order = 'asc'
    @order = 'desc' if params[:_order] == 'desc'

    @products = Product.order("name #{@order}")
    @sort = 'title'
    if params[:_sort] == 'price'
      @products = @products.reorder("price #{@order}")
      @sort = 'price'
    end

    @search = params[:title]
    @products = @products.where(["lower(name) = ?", @search.downcase]) unless @search.blank?
    @products = @products.order('name')
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <%= tag.title content_for?(:page_title) ? yield(:page_title) : 'HACK ME UP!' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <section class="section">
      <div class="container">

        <% if flash[:notice] %>
          <div class="notification is-info"> <button class="delete"></button> <%= flash[:notice] %> </div>
        <% end %>

        <% if flash[:alert] %>
          <div class="notification is-warning"> <button class="delete"></button> <%= flash[:alert] %> </div>
        <% end %>

        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/pages/health_check.html.erb
<h1 class="title"> <%= l @timestamp, format: :long %> </h1>

app/views/pages/login.html.erb
<div class="columns">
  <div class="column is-one-third">

    <div class="card">
      <div class="card-header">
        <h1 class="card-header-title"> Login </h1>
      </div>
      <div class="card-content bg-primary">

        <%= form_tag sign_in_url do |f| %>
          <div class="field">
            <%= label_tag :email, 'Usuario', class: 'label' %>
            <div class="control">
              <%= text_field_tag :email, '', placeholder: 'E-mail', class: 'input', autofocus: true %>
            </div>
          </div>

          <div class="field">
            <%= label_tag :password, 'Contraseña', class: 'label' %>
            <div class="control">
              <%= password_field_tag :password, '', class: 'input' %>
            </div>
          </div>

          <%= submit_tag 'Enviar', class: 'button is-primary is-fullwidth' %>
        <% end %>

      </div>
    </div>

  </div>
</div>

app/views/pages/welcome.html.erb
<h1 class="title"> <%= t :welcome %> </h1>

app/views/products/_product.html.erb
<div class="tile is-2">
  <div class="card">
    <div class="card-image">
      <%= image_tag product.image_url, title: product.name %>
    </div>
    <div class="card-content">
      <h1 class="title"> <%= product.name %> </h1>
      <p class="subtitle"> <%= number_to_currency product.price %> </p>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<h1 class="title"> Products </h1>

<div class="columns">
  <div class="column is-6">
    <div class="tabs">
      <ul>
        <%= tag.li class: "#{'is-active' if @search.blank?}" do %>
          <%= link_to "All products", products_url %> 
        <% end %>
        <%= tag.li class: "#{'is-active' if @search == 'apple'}" do %>
          <%= link_to "Apple", products_url(title: :apple) %> 
        <% end %>
      </ul>
    </div>
  </div>

  <div class="column is-3">
    <div class="buttons has-addons">
      <%= link_to 'Sort by title', products_url(_sort: :title, _order: @order), class: "button #{'is-active is-primary' if @sort == 'title'}" %>
      <%= link_to 'Sort by price', products_url(_sort: :price, _order: @order), class: "button #{'is-active is-primary' if @sort == 'price'}" %>
    </div>
  </div>

  <div class="column is-3">
    <div class="buttons has-addons">
      <%= link_to 'Ascending', products_url(_sort: @sort, _order: :asc), class: "button #{'is-active is-primary' if @order == 'asc'}" %>
      <%= link_to 'Descending', products_url(_sort: @sort, _order: :desc), class: "button #{'is-active is-primary' if @order == 'desc'}" %>
    </div>
  </div>
</div>

<div class="tile">
  <%= render @products[0..5] %>
</div>

<% if @products.count > 5 %>
  <div class="tile">
    <%= render @products[5..] %>
  </div>
<% end %>